[project]
name = "msdocs-python-flask-webapp-quickstart"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask==3.1.0",
    "gunicorn>=23.0.0",
    "requests>=2.32.5",
]
